sudo: required

services:
  - docker

before_install:
  - ./tester
  - docker build -t yusufali/rtorrent .
  - docker run --name sbox -dt yusufali/rtorrent sh

script:
  - docker exec sbox test/entry-start.sh
