sudo: required
services:
  - docker
before_install:
  - docker build -t yusufali/rtorrent .
  - docker run -d yusufali/rtorrent
  - docker ps -a
script:
  - echo 1
notifications:
  slack: 
    on_success: change
    on_failure: change
  email:
    on_success: never
    on_failure: change 
