sudo: required

services:
  - docker

before_install:
  - echo "COPY test /root/test/" >> Dockerfile
  - docker build -t yusufali/rtorrent .
  - docker run -it yusufali/rtorrent

script:
  - /root/test/entry-start.sh
