#!/bin/sh

rm -rf /root/.session/rtorrent.lock


cd /vpn
openvpn --config *.ovpn &
echo "nameserver 8.8.8.8" > /etc/resolv.conf

sleep 20
IP=`/sbin/ifconfig tun0 | grep "inet addr" | awk -F: '{print $2}' | awk '{print $1}'`
ip route replace 0.0.0.0/0 via $IP


lighttpd -f /etc/lighttpd/lighttpd.conf
rtorrent